name: Deploy rutgers repo to rutgers.tspace.in
on:
  push:
    branches:
      - tspace
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.TSPACE_FTP_SERVER }}
          username: ${{ secrets.TSPACE_FTP_USERNAME }}
          password: ${{ secrets.TSPACE_FTP_PASSWORD }}
          server-dir: rutgers.tspace.in/
          exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/src/**
          wp-content/plugins/rutgers-plugin/package.json
          wp-content/plugins/rutgers-plugin/package-lock.json
          wp-content/themes/rutgers/gulpfile.js
          wp-content/themes/rutgers/package-lock.json
          wp-content/themes/rutgers/package.json
          wp-content/themes/rutgers/postcss.config.js
          wp-content/themes/rutgers/tailwind.config.js
          wp-content/themes/rutgers/safelist.txt